name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env: 
        DATABASE_URL: '${{ secrets.DATABASE_URL }}'
      run: DATABASE_URL=$DATABASE_URL docker build . --file Dockerfile --tag docker-bot:latest
